name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: ManuLinares/setup-c3@v1
        with:
          version: 0.8.4

      - name: Test
        run: c3c test
